tdapp/urls.py
from django.urls import path
from . import views


app_name = 'tdapp'
urlpatterns = [
    path('', views.index, name='home'),

    path('create/', views.create_task, name='create'),
    path('update/<str:pk>', views.update_task, name='update'),
    path('delete/<str:pk>', views.delete_task, name='delete'),

    path('login', views.login_page, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('register', views.register_page, name='register'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('tdapp.urls')),
]

tdapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Guest(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=200, default='Untitled')
    creation_date = models.DateTimeField(auto_now_add=True, null=True)
    text = models.TextField()
    done = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name
        

tdapp/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'text', 'done']


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

tdapp/views.py
from django.shortcuts import render, redirect
from django.template import loader

from .models import *
from .forms import *
from .decorators import *

from django.contrib import messages

from django.contrib.auth.models import Group
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required


def index(request):

    try:
        tasks = Task.objects.filter(user=request.user)
    except TypeError:
        template = loader.get_template('tdapp/unauth.html')
        return HttpResponse(template.render())

    context = {'tasks': tasks}
    return render(request, 'index.html', context)


@login_required(login_url='login')
def create_task(request):

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('tdapp:home')
    form = TaskForm

    context = {'form': form}
    return render(request, 'tdapp/create_task.html', context)


@login_required(login_url='login')
def update_task(request, pk):

    task = Task.objects.get(id=pk)
    form = TaskForm(instance=task)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('/guest/' + str(task.user.id))

    context = {'form': form}
    return render(request, 'tdapp/create_task.html', context)


@login_required(login_url='login')
def delete_task(request, pk):

    task = Task.objects.get(id=pk)
    if request.method == 'POST':
        task.delete()
        return redirect('tdapp:home')

    context = {'task': task}
    return render(request, 'tdapp/delete_task.html', context)


@unauthenticated_user
def login_page(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('tdapp:home')
        else:
            messages.info(request, 'Username or password is incorrect')

    context = {}
    return render(request, 'tdapp/login.html', context)


@unauthenticated_user
def register_page(request):

    form = CreateUserForm
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            group = Group.objects.get(name='guest')
            user.groups.add(group)
            Guest.objects.create(
                user=user,
                name=username,
            )
            messages.success(request, f'Account {username} created successfully')
            return redirect('tdapp:login')
        else:
            pass

    context = {'form': form}
    return render(request, 'tdapp/register.html', context)


def logout_user(request):
    logout(request)
    return redirect('tdapp:login')

templates/index.html
{% extends 'tdapp/base.html' %}
{% block content %}

<div class="tasks">

    {% for task in tasks %}
    <div class="label">
    <h2>{{ task.name }}
    <p></p>
        <h4>Status:{% if task.done %} Done
        {% else %}In progress{% endif %}</h4>
        <span>{{ task.text }}</span>
    </h2>
  <p></p>
  <a href="{% url 'tdapp:update' task.id %}" class="btn btn-sm btn-info"
     style="width: 49%">Update</a>
  <a href="{% url 'tdapp:delete' task.id %}" class="btn btn-sm btn-danger"
     style="width: 49%">Delete</a>
  </div>
    {% endfor %}
<p></p>
    <a href="{% url 'tdapp:create' %}" class="btn btn-sm btn-success"
    style="width: 100%">Create</a>
</div>

{% endblock %}

templates/tdapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo</title>
        <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
        <link rel="stylesheet"
              type="text/css"
              href="{% static 'css/main.css' %}">
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <a class="navbar-brand" href="#">
          <img src="http://placehold.it/150x50?text=Logo" alt="">
        </a>
    <button class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarResponsive"
            aria-controls="navbarResponsive"
            aria-expanded="false"
            aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <h1>Hello, {{ request.user }} </h1>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'tdapp:home' %}">Home
                <span class="sr-only">(current)</span>
              </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tdapp:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tdapp:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tdapp:logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!-- Page Content -->
<div class="container">
  {% block content %}

  {% endblock %}
</div>
<!-- /.container -->


</body>
</html>

templates/tdapp/create_task.html
{% extends 'tdapp/base.html' %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="Submit" class="btn btn-sm btn-success">
</form>

{% endblock %}

templates/tdapp/delete_task.html
{% extends 'tdapp/base.html' %}
{% block content %}

    <p style="text-align: center">Are you sure you want to delete "{{ task }}"?</p>
<form action="{% url 'tdapp:delete' task.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="Confirm" id="add_word_button">
    <a href="{% url 'tdapp:home' %} "
       class="btn btn-sm"
       style="left: 60%;
       background-color: #1F78B4;
       padding: 0 0 0 0px;
       border-width: 1px">Cancel</a>
</form>

{% endblock %}

templates/tdapp/login.html
{% extends 'tdapp/base.html' %}
{% block content %}

<div class="container">
			<h3>Login</h3>

		<form action="#" method="POST">
            {% csrf_token %}
			<input type="text" name="username" placeholder="username" class="field">
			<input type="password" name="password" placeholder="password" class="field">
			<input type="submit" value="Login" class="btn btn-success"
            style="position: absolute; top: 27%; width: 22.8%; left: 39%;">
		</form>
	</div>
{% endblock %}

templates/tdapp/register.html
{% extends 'tdapp/base.html' %}
{% block content %}

			<h3>Register</h3>
		<form action="#" method="POST">
        {% csrf_token %}
{#			<input type="text" placeholder="username" class="field">#}
            {{ form.username }}
{#			<input type="password" placeholder="password" class="field">#}
            {{ form.password1 }}
{#            <input type="password" placeholder="confirm password" class="field">#}
            {{ form.password2 }}
			<input type="submit" value="Register Account" class="btn btn-success"
            style="position: absolute; top: 34%; width: 22.8%; left: 38.3%;">
		</form>

{% endblock %}

templates/tdapp/unauth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error 401</title>
    <link rel="stylesheet"
      type="text/css"
      href="{% static 'css/main.css' %}">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
</head>
<body style="background-color: #292929">
<div class="label">
    <h2 style="text-align: center">You need to create an account or login</h2>
    <div class="tasks">
      <a href="{% url 'tdapp:login' %}"
         class="btn btn-sm btn-info">Login</a>
      <a href="{% url 'tdapp:register' %}"
         class="btn btn-sm btn-info">Register</a>
    </div>

</div>
</body>
</html>

templates/tdapp/update_task.html
{% extends 'tdapp/base.html' %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form }}
</form>

{% endblock %}